name: spozzle
description: A puzzle about sports tournaments
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^1.2.2
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.17.0
  just_audio: ^0.9.18
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17
  material_design_icons_flutter: ^7.0.7296
  line_icons: ^2.0.1
  flutter_carousel_slider: ^1.0.8
  animated_text_kit: ^4.2.1

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  
dependency_overrides:
  intl: 0.19.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/icon/common/
    - assets/icon/android/
    - assets/images/audio_control/
    - assets/images/dashatar/gallery/
    - assets/images/dashatar/success/
    - assets/images/dashatar/littoral/
    - assets/images/dashatar/background_pattern/
    - assets/images/dashatar/west/
    - assets/images/dashatar/north/
    - assets/images/dashatar/northwest/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
          
    - family: Hakuna
      fonts:
        - asset: assets/fonts/HakunaRegular.ttf
          weight: 400
  
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/common/app-icon.png"
  image_path_ios_dark_transparent: "assets/icon/common/app-icon-transparent.png"
  image_path_android: "assets/icon/android/app-icon-android.png"
  adaptive_icon_background: "assets/icon/android/app-icon-background.png"
  adaptive_icon_foreground: "assets/icon/android/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/common/app-icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_android: "#ffffff"
  color_dark_android: "#121212"
  color_ios: "#ffffff"
  color_dark_ios: "#121212"
  color_web: "#ffffff"
  color_dark_web: "#121212"
  image: "assets/icon/android/app-icon-foreground.png"
