name: spozzle
description: A puzzle about sports tournaments
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^1.2.2
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.17.0
  just_audio: ^0.9.18
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17
  material_design_icons_flutter: ^7.0.7296
  line_icons: ^2.0.1
  flutter_carousel_slider: ^1.0.8
  animated_text_kit: ^4.2.1

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  
dependency_overrides:
  intl: 0.19.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
    - assets/images/dashatar/gallery/
    - assets/images/dashatar/success/
    - assets/images/dashatar/littoral/
    - assets/images/dashatar/background_pattern/
    - assets/images/dashatar/west/
    - assets/images/dashatar/north/
    - assets/images/dashatar/northwest/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
          
    - family: Hakuna
      fonts:
        - asset: assets/fonts/HakunaRegular.ttf
          weight: 400
